name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v1.0.0
        with:
            accoun: "${{ secrets.SNOWFLAKE_ACCOUNT }}"
            user: "${{ secrets.SNOWFLAKE_USER }}"
            password: "${{ secrets.SNOWFLAKE_PASSWORD }}"
            warehouse: COMPUTE_WH
            database: SNOWFLAKE_LEARNING_DB 
            schema: PUBLIC

      - name: Run SQL script
        run: snow sql -c default -f sql/create_tables.sql
