name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - name: Install Snowflake CLI
        run: pip install snowflake-cli
     
      - name: Configure Snowflake
        run: |
          umask 077
          mkdir -p ~/.snowflake
          echo "account = \"${{ secrets.SNOWFLAKE_ACCOUNT }}\"" > ~/.snowflake/config.toml
          echo "user = \"${{ secrets.SNOWFLAKE_USER }}\"" >> ~/.snowflake/config.toml
          echo "password = \"${{ secrets.SNOWFLAKE_PASSWORD }}\"" >> ~/.snowflake/config.toml
          echo "warehouse = COMPUTE_WH" >> ~/.snowflake/config.toml
          echo "database = SNOWFLAKE_LEARNING_DB" >> ~/.snowflake/config.toml
          echo "schema = PUBLIC" >> ~/.snowflake/config.toml
          chmod 600 ~/.snowflake/config.toml 

      - name: Run SQL script
        run: snow sql -c default -f sql/create_tables.sql
